# Copyright (C) 2011 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/samsung/axiom-common/setup-makefiles.sh

## axiom-common/common-proprietary-files.txt
PRODUCT_COPY_FILES += \
	vendor/samsung/axiom-common/proprietary/bin/mpdecision:system/bin/mpdecision \
	vendor/samsung/axiom-common/proprietary/vendor/lib/libqc-opt.so:system/vendor/lib/libqc-opt.so \
	vendor/samsung/axiom-common/proprietary/vendor/lib/libacdbloader.so:system/vendor/lib/libacdbloader.so \
	vendor/samsung/axiom-common/proprietary/vendor/lib/libaudcal.so:system/vendor/lib/libaudcal.so \
	vendor/samsung/axiom-common/proprietary/lib/libcsd-client.so:system/lib/libcsd-client.so \
	vendor/samsung/axiom-common/proprietary/bin/mm-qcamera-daemon:system/bin/mm-qcamera-daemon \
	vendor/samsung/axiom-common/proprietary/cameradata/datapattern_420sp.yuv:system/cameradata/datapattern_420sp.yuv \
	vendor/samsung/axiom-common/proprietary/cameradata/datapattern_front_420sp.yuv:system/cameradata/datapattern_front_420sp.yuv \
	vendor/samsung/axiom-common/proprietary/lib/hw/camera.vendor.msm8960.so:system/lib/hw/camera.vendor.msm8960.so \
	vendor/samsung/axiom-common/proprietary/lib/libchromatix_imx074_default_video.so:system/lib/libchromatix_imx074_default_video.so \
	vendor/samsung/axiom-common/proprietary/lib/libchromatix_imx074_preview.so:system/lib/libchromatix_imx074_preview.so \
	vendor/samsung/axiom-common/proprietary/lib/libchromatix_imx074_video_hd.so:system/lib/libchromatix_imx074_video_hd.so \
	vendor/samsung/axiom-common/proprietary/lib/libchromatix_imx074_zsl.so:system/lib/libchromatix_imx074_zsl.so \
	vendor/samsung/axiom-common/proprietary/lib/libchromatix_imx091_default_video.so:system/lib/libchromatix_imx091_default_video.so \
	vendor/samsung/axiom-common/proprietary/lib/libchromatix_imx091_preview.so:system/lib/libchromatix_imx091_preview.so \
	vendor/samsung/axiom-common/proprietary/lib/libchromatix_imx091_video_hd.so:system/lib/libchromatix_imx091_video_hd.so \
	vendor/samsung/axiom-common/proprietary/lib/libchromatix_mt9e013_default_video.so:system/lib/libchromatix_mt9e013_default_video.so \
	vendor/samsung/axiom-common/proprietary/lib/libchromatix_mt9e013_preview.so:system/lib/libchromatix_mt9e013_preview.so \
	vendor/samsung/axiom-common/proprietary/lib/libchromatix_ov2720_default_video.so:system/lib/libchromatix_ov2720_default_video.so \
	vendor/samsung/axiom-common/proprietary/lib/libchromatix_ov2720_preview.so:system/lib/libchromatix_ov2720_preview.so \
	vendor/samsung/axiom-common/proprietary/lib/libchromatix_s5k3l1yx_default_video.so:system/lib/libchromatix_s5k3l1yx_default_video.so \
	vendor/samsung/axiom-common/proprietary/lib/libchromatix_s5k3l1yx_hfr_120fps.so:system/lib/libchromatix_s5k3l1yx_hfr_120fps.so \
	vendor/samsung/axiom-common/proprietary/lib/libchromatix_s5k3l1yx_hfr_60fps.so:system/lib/libchromatix_s5k3l1yx_hfr_60fps.so \
	vendor/samsung/axiom-common/proprietary/lib/libchromatix_s5k3l1yx_hfr_90fps.so:system/lib/libchromatix_s5k3l1yx_hfr_90fps.so \
	vendor/samsung/axiom-common/proprietary/lib/libchromatix_s5k3l1yx_preview.so:system/lib/libchromatix_s5k3l1yx_preview.so \
	vendor/samsung/axiom-common/proprietary/lib/libchromatix_s5k3l1yx_video_hd.so:system/lib/libchromatix_s5k3l1yx_video_hd.so \
	vendor/samsung/axiom-common/proprietary/lib/libchromatix_s5k3l1yx_zsl.so:system/lib/libchromatix_s5k3l1yx_zsl.so \
	vendor/samsung/axiom-common/proprietary/lib/libchromatix_s5k4e1_default_video.so:system/lib/libchromatix_s5k4e1_default_video.so \
	vendor/samsung/axiom-common/proprietary/lib/libchromatix_s5k4e1_preview.so:system/lib/libchromatix_s5k4e1_preview.so \
	vendor/samsung/axiom-common/proprietary/lib/libgemini.so:system/lib/libgemini.so \
	vendor/samsung/axiom-common/proprietary/lib/libimage-jpeg-enc-omx-comp.so:system/lib/libimage-jpeg-enc-omx-comp.so \
	vendor/samsung/axiom-common/proprietary/lib/libimage-omx-common.so:system/lib/libimage-omx-common.so \
	vendor/samsung/axiom-common/proprietary/lib/libmmcamera_faceproc.so:system/lib/libmmcamera_faceproc.so \
	vendor/samsung/axiom-common/proprietary/lib/libmmcamera_frameproc.so:system/lib/libmmcamera_frameproc.so \
	vendor/samsung/axiom-common/proprietary/lib/libmmjpeg.so:system/lib/libmmjpeg.so \
	vendor/samsung/axiom-common/proprietary/lib/libmmmpod.so:system/lib/libmmmpod.so \
	vendor/samsung/axiom-common/proprietary/lib/libmmstillomx.so:system/lib/libmmstillomx.so \
	vendor/samsung/axiom-common/proprietary/lib/liboemcamera.so:system/lib/liboemcamera.so \
	vendor/samsung/axiom-common/proprietary/lib/libsecnativefeature.so:system/lib/libsecnativefeature.so \
	vendor/samsung/axiom-common/proprietary/bin/qseecomd:system/bin/qseecomd \
	vendor/samsung/axiom-common/proprietary/vendor/lib/libdrmdecrypt.so:system/vendor/lib/libdrmdecrypt.so \
	vendor/samsung/axiom-common/proprietary/vendor/lib/libdrmfs.so:system/vendor/lib/libdrmfs.so \
	vendor/samsung/axiom-common/proprietary/vendor/lib/libdrmtime.so:system/vendor/lib/libdrmtime.so \
	vendor/samsung/axiom-common/proprietary/vendor/lib/libQSEEComAPI.so:system/vendor/lib/libQSEEComAPI.so \
	vendor/samsung/axiom-common/proprietary/vendor/firmware/a300_pfp.fw:system/vendor/firmware/a300_pfp.fw \
	vendor/samsung/axiom-common/proprietary/vendor/firmware/a300_pm4.fw:system/vendor/firmware/a300_pm4.fw \
	vendor/samsung/axiom-common/proprietary/vendor/firmware/vidc_1080p.fw:system/vendor/firmware/vidc_1080p.fw \
	vendor/samsung/axiom-common/proprietary/lib/libloc_api_v02.so:system/lib/libloc_api_v02.so \
	vendor/samsung/axiom-common/proprietary/etc/srm.bin:system/etc/srm.bin \
	vendor/samsung/axiom-common/proprietary/lib/libhdcp2.so:system/lib/libhdcp2.so \
	vendor/samsung/axiom-common/proprietary/vendor/lib/libdivxdrm.so:system/vendor/lib/libdivxdrm.so \
	vendor/samsung/axiom-common/proprietary/vendor/lib/libI420colorconvert.so:system/vendor/lib/libI420colorconvert.so \
	vendor/samsung/axiom-common/proprietary/vendor/lib/libmm-color-convertor.so:system/vendor/lib/libmm-color-convertor.so \
	vendor/samsung/axiom-common/proprietary/vendor/lib/libmmosal.so:system/vendor/lib/libmmosal.so \
	vendor/samsung/axiom-common/proprietary/vendor/lib/libmmparser.so:system/vendor/lib/libmmparser.so \
	vendor/samsung/axiom-common/proprietary/bin/mm-pp-daemon:system/bin/mm-pp-daemon \
	vendor/samsung/axiom-common/proprietary/vendor/lib/libmm-abl.so:system/vendor/lib/libmm-abl.so \
	vendor/samsung/axiom-common/proprietary/vendor/lib/libmm-abl-oem.so:system/vendor/lib/libmm-abl-oem.so \
	vendor/samsung/axiom-common/proprietary/bin/ds_fmc_appd:system/bin/ds_fmc_appd \
	vendor/samsung/axiom-common/proprietary/bin/qmuxd:system/bin/qmuxd \
	vendor/samsung/axiom-common/proprietary/bin/rild:system/bin/rild \
	vendor/samsung/axiom-common/proprietary/bin/rmt_storage:system/bin/rmt_storage \
	vendor/samsung/axiom-common/proprietary/lib/libatparser.so:system/lib/libatparser.so \
	vendor/samsung/axiom-common/proprietary/lib/libfactoryutil.so:system/lib/libfactoryutil.so \
	vendor/samsung/axiom-common/proprietary/lib/libomission_avoidance.so:system/lib/libomission_avoidance.so \
	vendor/samsung/axiom-common/proprietary/lib/libreference-ril.so:system/lib/libreference-ril.so \
	vendor/samsung/axiom-common/proprietary/lib/libsecril-client.so:system/lib/libsecril-client.so \
	vendor/samsung/axiom-common/proprietary/lib/hw/sensors.msm8960.so:system/lib/hw/sensors.msm8960.so \
	vendor/samsung/axiom-common/proprietary/bin/time_daemon:system/bin/time_daemon \
	vendor/samsung/axiom-common/proprietary/lib/libtime_genoff.so:system/lib/libtime_genoff.so \
	vendor/samsung/axiom-common/proprietary/vendor/lib/drm/libdrmwvmplugin.so:system/vendor/lib/drm/libdrmwvmplugin.so \
	vendor/samsung/axiom-common/proprietary/vendor/lib/libwvm.so:system/vendor/lib/libwvm.so \
